### ISSUE TITLE
Rekursiv Search functionality missing

### ISSUE THREAD

**Issue by therealsimwoe** [DevEpos/abap-search-tools#32]
Dear team,

in the current version of the ABAP Object search the following functionality which would help developers even more is unfortunately missing: There is no "recursive search implemented" to find really ALL CDS-Views based on a certain filter pattern.

An example can be given as follows:

If you execute the search with the filter: **from: vbap** you will find the CDS-View: I_SalesDocumentItem
Based on the Icon I can see that I_SalesDocumentItem is also used in another CDS - but I would like to also see this directly in the resultset.
The expectation would be to directly find with the filter: from: vbap also the CDS-View: I_SALESORDERITEM.

This is the one which is selecting from I_SalesDocumentItem.

Especially if you combine the filter from: vbap with other filters like: **api: use_in_cloud_development** this would be really helpful to have a "recursive search".

Is this something that could be implemented? Or is there an easy workaround for?

Thank you!

**Comment by stockbal** [comment]
Hi @therealsimwoe,

the feature you are looking for will be shipped in the next version which is in its final development phase 😊.

Kind regards,
Ludwig

**Comment by therealsimwoe** [comment]
Hi Ludwig,

thanks for the feedback. Then I am even more looking forward to the next version!
Can we somehow link the issue to the release version? (not that much experienced with Github yet 😄 )

Best regards!

**Comment by stockbal** [comment]
Implemented with version 2.0.0
